/** ======================================================================== **\
| Version:
1.0.0

| License:
Copyright (c) 2016 Double V

This software is provided 'as-is', without any express or implied
warranty. In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1.	The origin of this software must not be misrepresented; you must not
	claim that you wrote the original software. If you use this software
	in a product, an acknowledgement in the product documentation would be
	appreciated but is not required.
2.	Altered source versions must be plainly marked as such, and must not be
	misrepresented as being the original software.
3.	This notice may not be removed or altered from any source distribution.
\** ======================================================================== **/


#if defined _inc_tdw_colorlist
	#undef _inc_tdw_colorlist
#endif

#if defined _TDW_CLLIB__COLORLIST
	#endinput
#endif

#define _TDW_CLLIB__COLORLIST

#define @COLOR@ALICEBLUE<%1,%2>							%1F0F8FF%2
#define @COLOR@ANTIQUEWHITE<%1,%2>						%1FAEBD7%2
#define @COLOR@AQUA<%1,%2>								%100FFFF%2
#define @COLOR@AQUAMARINE<%1,%2>						%17FFFD4%2
#define @COLOR@AZURE<%1,%2>								%1F0FFFF%2
#define @COLOR@BEIGE<%1,%2>								%1F5F5DC%2
#define @COLOR@BISQUE<%1,%2>							%1FFE4C4%2
#define @COLOR@BLACK<%1,%2>								%1000000%2
#define @COLOR@BLANCHEDALMOND<%1,%2>					%1FFEBCD%2
#define @COLOR@BLUE<%1,%2>								%10000FF%2
#define @COLOR@BLUEVIOLET<%1,%2>						%18A2BE2%2
#define @COLOR@BROWN<%1,%2>								%1A52A2A%2
#define @COLOR@BURLYWOOD<%1,%2>							%1DEB887%2
#define @COLOR@CADETBLUE<%1,%2>							%15F9EA0%2
#define @COLOR@CHARTREUSE<%1,%2>						%17FFF00%2
#define @COLOR@CHOCOLATE<%1,%2>							%1D2691E%2
#define @COLOR@CORAL<%1,%2>								%1FF7F50%2
#define @COLOR@CORNFLOWERBLUE<%1,%2>					%16495ED%2
#define @COLOR@CORNSILK<%1,%2>							%1FFF8DC%2
#define @COLOR@CRIMSON<%1,%2>							%1DC143C%2
#define @COLOR@CYAN<%1,%2>								%100FFFF%2
#define @COLOR@DARKBLUE<%1,%2>							%100008B%2
#define @COLOR@DARKCYAN<%1,%2>							%1008B8B%2
#define @COLOR@DARKGOLDENROD<%1,%2>						%1B8860B%2
#define @COLOR@DARKGRAY<%1,%2>							%1A9A9A9%2
#define @COLOR@DARKGREY<%1,%2>							%1A9A9A9%2
#define @COLOR@DARKGREEN<%1,%2>							%1006400%2
#define @COLOR@DARKKHAKI<%1,%2>							%1BDB76B%2
#define @COLOR@DARKMAGENTA<%1,%2>						%18B008B%2
#define @COLOR@DARKOLIVEGREEN<%1,%2>					%1556B2F%2
#define @COLOR@DARKORANGE<%1,%2>						%1FF8C00%2
#define @COLOR@DARKORCHID<%1,%2>						%19932CC%2
#define @COLOR@DARKRED<%1,%2>							%18B0000%2
#define @COLOR@DARKSALMON<%1,%2>						%1E9967A%2
#define @COLOR@DARKSEAGREEN<%1,%2>						%18FBC8F%2
#define @COLOR@DARKSLATEBLUE<%1,%2>						%1483D8B%2
#define @COLOR@DARKSLATEGRAY<%1,%2>						%12F4F4F%2
#define @COLOR@DARKSLATEGREY<%1,%2>						%12F4F4F%2
#define @COLOR@DARKTURQUOISE<%1,%2>						%100CED1%2
#define @COLOR@DARKVIOLET<%1,%2>						%19400D3%2
#define @COLOR@DEEPPINK<%1,%2>							%1FF1493%2
#define @COLOR@DEEPSKYBLUE<%1,%2>						%100BFFF%2
#define @COLOR@DIMGRAY<%1,%2>							%1696969%2
#define @COLOR@DIMGREY<%1,%2>							%1696969%2
#define @COLOR@DODGERBLUE<%1,%2>						%11E90FF%2
#define @COLOR@FIREBRICK<%1,%2>							%1B22222%2
#define @COLOR@FLORALWHITE<%1,%2>						%1FFFAF0%2
#define @COLOR@FORESTGREEN<%1,%2>						%1228B22%2
#define @COLOR@FUCHSIA<%1,%2>							%1FF00FF%2
#define @COLOR@GAINSBORO<%1,%2>							%1DCDCDC%2
#define @COLOR@GHOSTWHITE<%1,%2>						%1F8F8FF%2
#define @COLOR@GOLD<%1,%2>								%1FFD700%2
#define @COLOR@GOLDENROD<%1,%2>							%1DAA520%2
#define @COLOR@GRAY<%1,%2>								%1808080%2
#define @COLOR@GREY<%1,%2>								%1808080%2
#define @COLOR@GREEN<%1,%2>								%1008000%2
#define @COLOR@GREENYELLOW<%1,%2>						%1ADFF2F%2
#define @COLOR@HONEYDEW<%1,%2>							%1F0FFF0%2
#define @COLOR@HOTPINK<%1,%2>							%1FF69B4%2
#define @COLOR@INDIANRED<%1,%2>							%1CD5C5C%2
#define @COLOR@INDIGO<%1,%2>							%14B0082%2
#define @COLOR@IVORY<%1,%2>								%1FFFFF0%2
#define @COLOR@KHAKI<%1,%2>								%1F0E68C%2
#define @COLOR@LAVENDER<%1,%2>							%1E6E6FA%2
#define @COLOR@LAVENDERBLUSH<%1,%2>						%1FFF0F5%2
#define @COLOR@LAWNGREEN<%1,%2>							%17CFC00%2
#define @COLOR@LEMONCHIFFON<%1,%2>						%1FFFACD%2
#define @COLOR@LIGHTBLUE<%1,%2>							%1ADD8E6%2
#define @COLOR@LIGHTCORAL<%1,%2>						%1F08080%2
#define @COLOR@LIGHTCYAN<%1,%2>							%1E0FFFF%2
#define @COLOR@LIGHTGOLDENRODYELLOW<%1,%2>				%1FAFAD2%2
#define @COLOR@LIGHTGRAY<%1,%2>							%1D3D3D3%2
#define @COLOR@LIGHTGREY<%1,%2>							%1D3D3D3%2
#define @COLOR@LIGHTGREEN<%1,%2>						%190EE90%2
#define @COLOR@LIGHTPINK<%1,%2>							%1FFB6C1%2
#define @COLOR@LIGHTSALMON<%1,%2>						%1FFA07A%2
#define @COLOR@LIGHTSEAGREEN<%1,%2>						%120B2AA%2
#define @COLOR@LIGHTSKYBLUE<%1,%2>						%187CEFA%2
#define @COLOR@LIGHTSLATEGRAY<%1,%2>					%1778899%2
#define @COLOR@LIGHTSLATEGREY<%1,%2>					%1778899%2
#define @COLOR@LIGHTSTEELBLUE<%1,%2>					%1B0C4DE%2
#define @COLOR@LIGHTYELLOW<%1,%2>						%1FFFFE0%2
#define @COLOR@LIME<%1,%2>								%100FF00%2
#define @COLOR@LIMEGREEN<%1,%2>							%132CD32%2
#define @COLOR@LINEN<%1,%2>								%1FAF0E6%2
#define @COLOR@MAGENTA<%1,%2>							%1FF00FF%2
#define @COLOR@MAROON<%1,%2>							%1800000%2
#define @COLOR@MEDIUMAQUAMARINE<%1,%2>					%166CDAA%2
#define @COLOR@MEDIUMBLUE<%1,%2>						%10000CD%2
#define @COLOR@MEDIUMORCHID<%1,%2>						%1BA55D3%2
#define @COLOR@MEDIUMPURPLE<%1,%2>						%19370DB%2
#define @COLOR@MEDIUMSEAGREEN<%1,%2>					%13CB371%2
#define @COLOR@MEDIUMSLATEBLUE<%1,%2>					%17B68EE%2
#define @COLOR@MEDIUMSPRINGGREEN<%1,%2>					%100FA9A%2
#define @COLOR@MEDIUMTURQUOISE<%1,%2>					%148D1CC%2
#define @COLOR@MEDIUMVIOLETRED<%1,%2>					%1C71585%2
#define @COLOR@MIDNIGHTBLUE<%1,%2>						%1191970%2
#define @COLOR@MINTCREAM<%1,%2>							%1F5FFFA%2
#define @COLOR@MISTYROSE<%1,%2>							%1FFE4E1%2
#define @COLOR@MOCCASIN<%1,%2>							%1FFE4B5%2
#define @COLOR@NAVAJOWHITE<%1,%2>						%1FFDEAD%2
#define @COLOR@NAVY<%1,%2>								%1000080%2
#define @COLOR@OLDLACE<%1,%2>							%1FDF5E6%2
#define @COLOR@OLIVE<%1,%2>								%1808000%2
#define @COLOR@OLIVEDRAB<%1,%2>							%16B8E23%2
#define @COLOR@ORANGE<%1,%2>							%1FFA500%2
#define @COLOR@ORANGERED<%1,%2>							%1FF4500%2
#define @COLOR@ORCHID<%1,%2>							%1DA70D6%2
#define @COLOR@PALEGOLDENROD<%1,%2>						%1EEE8AA%2
#define @COLOR@PALEGREEN<%1,%2>							%198FB98%2
#define @COLOR@PALETURQUOISE<%1,%2>						%1AFEEEE%2
#define @COLOR@PALEVIOLETRED<%1,%2>						%1DB7093%2
#define @COLOR@PAPAYAWHIP<%1,%2>						%1FFEFD5%2
#define @COLOR@PEACHPUFF<%1,%2>							%1FFDAB9%2
#define @COLOR@PERU<%1,%2>								%1CD853F%2
#define @COLOR@PINK<%1,%2>								%1FFC0CB%2
#define @COLOR@PLUM<%1,%2>								%1DDA0DD%2
#define @COLOR@POWDERBLUE<%1,%2>						%1B0E0E6%2
#define @COLOR@PURPLE<%1,%2>							%1800080%2
#define @COLOR@REBECCAPURPLE<%1,%2>						%1663399%2
#define @COLOR@RED<%1,%2>								%1FF0000%2
#define @COLOR@ROSYBROWN<%1,%2>							%1BC8F8F%2
#define @COLOR@ROYALBLUE<%1,%2>							%14169E1%2
#define @COLOR@SADDLEBROWN<%1,%2>						%18B4513%2
#define @COLOR@SALMON<%1,%2>							%1FA8072%2
#define @COLOR@SANDYBROWN<%1,%2>						%1F4A460%2
#define @COLOR@SEAGREEN<%1,%2>							%12E8B57%2
#define @COLOR@SEASHELL<%1,%2>							%1FFF5EE%2
#define @COLOR@SIENNA<%1,%2>							%1A0522D%2
#define @COLOR@SILVER<%1,%2>							%1C0C0C0%2
#define @COLOR@SKYBLUE<%1,%2>							%187CEEB%2
#define @COLOR@SLATEBLUE<%1,%2>							%16A5ACD%2
#define @COLOR@SLATEGRAY<%1,%2>							%1708090%2
#define @COLOR@SLATEGREY<%1,%2>							%1708090%2
#define @COLOR@SNOW<%1,%2>								%1FFFAFA%2
#define @COLOR@SPRINGGREEN<%1,%2>						%100FF7F%2
#define @COLOR@STEELBLUE<%1,%2>							%14682B4%2
#define @COLOR@TAN<%1,%2>								%1D2B48C%2
#define @COLOR@TEAL<%1,%2>								%1008080%2
#define @COLOR@THISTLE<%1,%2>							%1D8BFD8%2
#define @COLOR@TOMATO<%1,%2>							%1FF6347%2
#define @COLOR@TURQUOISE<%1,%2>							%140E0D0%2
#define @COLOR@VIOLET<%1,%2>							%1EE82EE%2
#define @COLOR@WHEAT<%1,%2>								%1F5DEB3%2
#define @COLOR@WHITE<%1,%2>								%1FFFFFF%2
#define @COLOR@WHITESMOKE<%1,%2>						%1F5F5F5%2
#define @COLOR@YELLOW<%1,%2>							%1FFFF00%2
#define @COLOR@YELLOWGREEN<%1,%2>						%19ACD32%2



#define COLOR%0<%1> (@COLOR@%1<0x,ff>)
#define SCOLOR%0<%1> (#@COLOR@%1<\x7B;,\x7D;>)
